/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseinvpatc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author alexb
 */
public class Confirm extends javax.swing.JFrame {
    private String activeUser;
    private DataConnect connect;
    private JTable jTabel1;
    private int toadd;
    private SelectOption options;
    private JTable jTable1;
    private Savepoint savePoint1;
    private String compName;
    private InvDetails prev;

    /**
     * Creates new form Confirm
     */
    public Confirm() {
        initComponents();
        
        description.setDocument(new JtextLimit(200));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        label1 = new java.awt.Label();
        Ok = new javax.swing.JButton();
        description = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Please Ener a breif description or any notes");

        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
              int ID;
        if (description.getText().isEmpty()) {
            description.setText("Null");
        }
        toadd = jTable1.getRowCount();
        if (toadd == 0) {
            this.options.setVisible(true);
            this.dispose();
            return;
        }
        Connection mycon = this.connect.getConnect();
        try {
            savePoint1 = mycon.setSavepoint("Savepoint1");
        } catch (SQLException ex) {

        }
        try {
            PreparedStatement pstmt = mycon.prepareStatement("insert into invsheet(invID,businessName,description,currentDate)values(null,?,?, now())");
            pstmt.setString(2,this.description.getText());
            pstmt.setString(1, this.compName);
            pstmt.executeUpdate();

            pstmt = mycon.prepareStatement("SELECT LAST_INSERT_ID() from invsheet");

            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                 ID  = rs.getInt(1);
                
                for (int i = 0; i < this.toadd; i++) {
                    pstmt = mycon.prepareStatement("insert into invdetails(invID,ItemName,ManfName,supplier,quantity,par,price)\n"
                            + "values(?,?,?,?,?,?,?)");
                    pstmt.setInt(1, ID);
                 //   System.out.println(this.jTable1.getValueAt(i, 0));
                    pstmt.setString(2, (String) this.jTable1.getValueAt(i, 0));
                    pstmt.setString(3, (String) this.jTable1.getValueAt(i, 1));
                    pstmt.setString(4, (String) this.jTable1.getValueAt(i, 2));
                    pstmt.setInt(5, (int) this.jTable1.getValueAt(i, 3));
                    pstmt.setInt(6, (int) this.jTable1.getValueAt(i, 4));
                    pstmt.setFloat(7, (float) this.jTable1.getValueAt(i, 5));
                    pstmt.executeUpdate();
                    SelectOption options = new SelectOption();
             options.setDataConect(this.connect);
             options.setVisible(true);
             options.setActiveUser(this.activeUser);
				options.fillTable();
          
                }
            }

            mycon.commit();

        } catch (SQLException ex) {
            try {
                mycon.rollback(savePoint1);
            } catch (SQLException ex1) {
                Logger.getLogger(InvDetails.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(InvDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
       

        
         

        this.dispose();
    }//GEN-LAST:event_OkActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.prev.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ok;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField description;
    private java.awt.Label label1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

    void SetActiveUser(String activeUser) {
       this.activeUser =activeUser;
    }

    void setConnect(DataConnect connect) {
      this.connect = connect;
    }

    void setTable(JTable jTable1) {
        this.jTable1= jTable1;
    }

    void setSelectopt(SelectOption options) {
     this.options = options;
    }

    void setComp(String compName) {
        this.compName=compName;
    }

    void SetPrev(InvDetails aThis) {
      this.prev =aThis;
    }
}
